services:
  postgres:
    env_file:
      - .env
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

  7am-club:
    build:
      context: .
    command: npm run start:dev
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db-data:
